### ISSUE TITLE
Suggestion: Add PixelFed

### ISSUE THREAD

**Issue by dansup** [thefederationinfo/the-federation.info#141]
Hello,

I am the developer behind the [PixelFed](https://pixelfed.org) project and am working on finishing federation support soon.

The project [does support NodeInfo](https://github.com/dansup/pixelfed/blob/dev/app/Http/Controllers/FederationController.php#L52-L110), using the /.well-known/nodeinfo URI.

Example nodeinfos:
[pixelfed.social/api/nodeinfo/2.0.json](https://pixelfed.social/api/nodeinfo/2.0.json)
[pix.hostux.social/api/nodeinfo/2.0.json](https://pix.hostux.social/api/nodeinfo/2.0.json)
[pxlfd.me/api/nodeinfo/2.0.json](https://pxlfd.me/api/nodeinfo/2.0.json)
[pix.tedomum.net/api/nodeinfo/2.0.json](https://pix.tedomum.net/api/nodeinfo/2.0.json)

**Comment by jaywink** [comment]
Hey! Thanks for reporting. Since PixelFed implements NodeInfo, registering worked without any changes :+1: I added your logo and some project info, please let me know (here in issues or chat) if something needs changing: https://the-federation.info/pixelfed

Btw, planning on exposing counts of active users? NodeInfo supports monthly and half year active counts. Basically the counts should be "count of users logged in during the last month/half year". If you track that it would be cool to have those exposed too to contribute to the overall stats.
