### ISSUE TITLE
Funny Mastodon graphs

### ISSUE THREAD

**Issue by Niektory** [thefederationinfo/the-federation.info#142]
Mastodon graphs display some _curious_ properties of time.

![screenshot_2018-07-04_13-49-33_](https://user-images.githubusercontent.com/4470900/42276231-630c37f2-7f93-11e8-8a4d-f7297915200d.png)

**Comment by jaywink** [comment]
Haha, yes, indeed. Interesting code in that graphing library to draw like that.

I think, since the-federation.info expanded to other protocols recently, thus jumping quite a big amount in all the numbers, that the default graphs should show only from the time that this jump happened - to make them make any sense. There could be a "show full history" link of course.

I'll keep this open until this default behaviour is changed.
