### ISSUE TITLE
Missing icons for platforms

### ISSUE THREAD

**Issue by xuv** [thefederationinfo/the-federation.info#181]
On the IndexPage, there are a few platform icons that are missing. The static files just don't exist. And instead, the UI displays the `alt` text property for the the missing image files, making the info redundant and the icon column quite wide.

After some research, It seems that an icon name is stored in the database even if the icon does not exist: https://github.com/thefederationinfo/the-federation.info/blob/72c11c2adaee1d133a71730d446ab6852a4567ba/thefederation/models/platform.py#L38-L39

And that value is returned to the front-end and helps create a link to a static asset that will not exist for some platforms.
https://github.com/thefederationinfo/the-federation.info/blob/72c11c2adaee1d133a71730d446ab6852a4567ba/src/components/PlatformTableRow.vue#L92-L93

What would be the best strategy to fix this. Any suggestion?

**Comment by jaywink** [comment]
Hey! I guess there are two ways of going towards this.

1) Add icons manually for each platform via git. This is how I've done it so far but since new platforms pop up all the time and some platforms change their icons, the current situation is not too good. It would fix the current data of course.

2) Enhance the Django admin page for platforms so that an icon can be uploaded there. This would move the icons from git to uploaded media. It would allow any site admin to maintain icons without needing to go through a code update process. Maybe in the future some object based permissions could be applied to allow platform maintainers to maintain the data of their own platform.

I would prefer the latter but anything to fix the current situation is also welcome.

**Comment by jaywink** [comment]
Fixed, or well, made better.
