### ISSUE TITLE
Very high loading time

### ISSUE THREAD

**Issue by davidak** [thefederationinfo/the-federation.info#213]
![Screenshot from 2020-01-12 03-02-43](https://user-images.githubusercontent.com/91113/72213066-b6abf080-34e8-11ea-90a6-df8d81b8b2d2.png)

The data takes very long to load.

For example https://the-federation.info/mastodon took 38 seconds. That is unacceptable for a website. Even more than 1 second makes a bad user experience.

It seems the data is loaded every time from a database or fetched live?

Maybe you can use some caching.

It's probably better to have data that is some minutes old than wait half a minute for the site.

**Comment by jaywink** [comment]
Yep the API is designed rather poorly. Once I have the time, I'm going to rewrite it in a cleaner way and clean also the frontend side in how it stores the API results. Currently there isn't much I can do due to time constraints but hopefully within a few months I should be able to work on this.

Related #187 and #176

**Comment by codingotaku** [comment]
After going through the queries, I feel adding pagination for nodes will help reduce the load time for this page.
Also, the page displays content only after all queries are completed - this has to be changed to have a more dynamic UI and the user don't have to wait till all nodes are loaded anyway...
