### ISSUE TITLE
Some nodes still listed as mastodon

### ISSUE THREAD

**Issue by jaywink** [thefederationinfo/the-federation.info#214]
For example Feneas friendica https://the-federation.info/node/friendica.feneas.org

![Selection_480](https://user-images.githubusercontent.com/1174866/73786904-d90cf300-47a2-11ea-9896-e10bded750a5.png)

**Comment by ingoj** [comment]
It seems that some nodes reliably hitting this issue, like atwa.ca. That host doesn't serve https://atwa.ca/.well-known/nodeinfo but only https://atwa.ca/nodeinfo/1.0 or /2.0 whileas Nerdica.net serves https://nerdica.net/.well-known/nodeinfo which links to https://nerdica.net/nodeinfo/1.0 or /2.0 then. 

Not sure if that might be the root cause, but when for some reasons /.well-known/nodeinfo is not reachable, it appears to me that the scripts fallback to the Mastodon default of using https://domain.tld/nodeinfo/2.0 - the script then interprets the availability of /nodeinfo/2.0 as belonging to Mastodon.

**Comment by ingoj** [comment]
JFTR: 
Those Friendica sites can be easily identified under Mastodon list when searching for year.month version, e.g. 2020.12 or 2021.01 or similar.

**Comment by weex** [comment]
https://friendica.pnw.social/.well-known/nodeinfo is another live example
