### ISSUE TITLE
Mastodon don't uses OStatus anymore

### ISSUE THREAD

**Issue by c-cesar** [thefederationinfo/the-federation.info#217]
Since version 3.0 Mastodon don't uses OStatus protocol, but mastodon instances are included in OStatus statistics.

Ref: https://github.com/tootsuite/mastodon/issues/10740

**Comment by jaywink** [comment]
Should be fixed by https://git.feneas.org/jaywink/federation/commit/50a3e376ddc91876449aedb745f2fc6228e7549d#745a6c8ca0bf1a9243c3ca04737155c723e3fee1_83_82 - just deploying in a bit. Will keep this open for a few days to see the data change since of course we need to actually fetch all mastodon instances.

Thanks for reporting.

**Comment by jaywink** [comment]
Seems to be working, data is rolling over slowly as sites get fetched :+1:
