### ISSUE TITLE
The-federation,info is giving the impression the fediverse is shrinking

### ISSUE THREAD

**Issue by wiki-me** [thefederationinfo/the-federation.info#237]
see [Example A](https://lemmy.ml/post/46311) and [Example B](https://lemmy.ml/post/41211/comment/18787) (i also saw it happen on reddit). basically they see the number of active users is shrinking but platforms such a pleroma and peertube (until recently) are growing but don’t report active users.

Also there could be a migration from more establish platforms that do report active users but are actually shrinking like diaspora or mastodon to platform that don’t report it such as pleroma or lemmy.

I have two ideas about how to possibly resolve this:

1) change “active users” to “confirmed active users” .

2) have a “?” or “!” icon next to the active users stats, hovering over it will just show a pop up saying the number is partial and maybe give a list of services that don’t count active users (could also be just a link to a page).

**Comment by nemobis** [comment]
I have a hard time believing the title of this issue: "The-federation.info is giving the impression the fediverse is shrinking". At any reasonable reading, the main page chart shows a rather flat number of users:

![Screenshot_20210227_113211](https://user-images.githubusercontent.com/901528/109383523-9fe47b00-78ef-11eb-89b7-6763b317e1a2.png)

It seems some people may be misreading the chart due to statistical illiteracy or other issues, but I don't think anything in the charts themselves will change that. There's already a quite visible:

> Disclaimer: These counts do not reflect the whole network due to the opt-in nature of the statistics.

**Comment by wiki-me** [comment]
It seems to have picked up a little since i reported it, and even now if you look at the start of the chart you will 1.4M and then at the end of the chart 1.27M ( a moderate decline). I think suggestion 2 i made would reduce the risk of people making that mistake drasticially (while also showing what services don't report active users, which might encourage them to report it).

You should'nt need to know statistics to interpret the chart, and people are making the assumption that every service that reports it's nodes also reports active users which is a reasonable assumption but a false one. In general i also think software should have a good UX and try to reasonably prevent users from "shooting themselves in the foot".

But the project now is in low maintenance mode and unless you plan on helping maintaining this project i think this debate is probably a waste of time.
