### ISSUE TITLE
Collect Ideas for Rewrite

### ISSUE THREAD

**Issue by 6543** [thefederationinfo/the-federation.info#283]
*summary will be written once we got enough consensus*

**Comment by 6543** [comment]
I would like to ...:
... frontend in Vue3 & Vite
... backend in go/rust with rest api

**Comment by 6543** [comment]
hot topic we need more data to make a well based decision:
 - should the graph/diagram rendering happen server side or client side

**Comment by Minoru** [comment]
Ideas as in "refactoring", or ideas as in "improvements"?

As far as improvements go, I'd like to see the-federation pulling data from nodes.fediverse.party, fediverse.observer and other sites that have Fediverse crawlers.

Regarding graphs, I think it makes sense to render them once, after node polling is done, so server-side rendering. But I think speeding up the API is much, much more important, because it's the reason the site is so slow right now (as far as I understand).

**Comment by mmahmoudian** [comment]
Few suggestions:
- add categories to the "Projects" (e.g blogging, video, audio, relay, ...)
- add separate lines for each of the categories above in a separate graph
- collect some statistics about number of bots (at least those that have declared in their profile)
- use [D3js](https://d3js.org/) for plotting on client side (addresses [the question](https://github.com/thefederationinfo/the-federation.info/issues/283#issuecomment-1118681377) above)

**Comment by 6543** [comment]
-> https://codeberg.org/thefederationinfo/the-federation.info/issues/283
