### ISSUE TITLE
Count/list also GNUSocial nodes ?

### ISSUE THREAD

**Issue by strk** [thefederationinfo/the-federation.info#66]
Should GNUSocial nodes be considered part of the federation too ?
See https://gnu.io/social/

**Comment by Flaburgan** [comment]
Gnusocial does not implement the federation protocol.

**Comment by jaywink** [comment]
> Gnusocial does not implement the federation protocol.

You mean the Diaspora protocol.

Yes, currently when saying "The Federation", we mean servers implementing the Diaspora protocol. IMHO that doesn't mean that has to always be true. In the coming up refresh of the site this is still a central theme, but for the long term future it would be nice to not be limited by this. We could for example show different networks per protocol. Some networks would overlap since for example Friendica speaks to both GNUSocial and DIaspora natively.

Let's leave this for future consideration. Ideas welcome :)

**Comment by strk** [comment]
Different network per protocol sounds good, and having statistics about which protocol is more supported would also be interesting.

**Comment by jaywink** [comment]
GNU Social is adding support for NodeInfo, already 4 development version nodes are registered. Will close this once the support rolls out on GNU Social side fully.

**Comment by jaywink** [comment]
Anyone have a list of GNU Social servers?

**Comment by Dragnucs** [comment]
There are many. A few to start with:

- quitter.is
- quitter.no
- quitter.es
- quitter.im
- 2mb.social
- algonoise.social
- anonymous.wtf
- shitposter.club
- sealion.club
- pl.smuglo.li (pleroma)
- gnusocial.net
- gnusocial.cc
- loadaverage.org
- social.bitcast.info

**Comment by jaywink** [comment]
GS requires a plugin for NodeInfo to be exposed, see [this issue](https://git.gnu.io/gnu/gnu-social/issues/317). I'm closing this issue here as technically GS can be registered, but the servers just need to add the plugin.
